### ISSUE TITLE
Reroute of gnome-browser-extension (chrome-gnome-shell) fork network

### ISSUE THREAD

**Issue by nE0sIghT** [kirrmann/Faster-Feedly#1]
Hello, Stefan!

First of all sorry for unrelated issue, but issues are disabled in the https://github.com/kirrmann/chrome-gnome-shell project.

Some time ago you contributed to GNOME/chrome-gnome-shell project [1][2] by creating a fork and PRs.
Due to `GNOME/chrome-gnome-shell` project rename to `GNOME/gnome-browser-extension` it's Github mirror was deleted making your fork the root of fork's network.

To restore my project as root of network I need to get your approval first (this is Github Support requirement).
Could you please approve transition of root network to my project https://github.com/nE0sIghT/gnome-browser-extension-mirror?

[1] https://github.com/nE0sIghT/chrome-gnome-shell/pull/2
[2] https://github.com/nE0sIghT/chrome-gnome-shell/pull/3

**Comment by kirrmann** [comment]
Hi,

sorry for the inconvenience. How can I give you this approval? Should I
just delete my fork?

Kinds regards
Stefan

**Comment by nE0sIghT** [comment]
Thanks for fast response!  
Something like "I approve" would be enough - I will give link to this issue to Github's Support.

**Comment by kirrmann** [comment]
I approve that https://github.com/nE0sIghT/gnome-browser-extension-mirror will be the root of network

**Comment by nE0sIghT** [comment]
Stefan, thanks!
